apiVersion: v1
kind: Namespace
metadata:
  name: taina-kubishi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: taina-kubishi
  name: taina-kubishi-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taina-kubishi-service
      app.kubernetes.io/part-of: taina-kubishi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: taina-kubishi-service
        app.kubernetes.io/part-of: taina-kubishi
    spec:
      containers:
        - name: service
          image: jaredraycoleman/tainacoleman.com:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: FLASK_ENV
              value: "production"
            - name: DEPLOY_ID # for easy re-deployment
              value: DEPLOYID-02474ebde79915c470dc2cffb40cc6cf
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  namespace: taina-kubishi
  name: taina-kubishi-service
spec:
  selector:
    app.kubernetes.io/name: taina-kubishi-service
    app.kubernetes.io/part-of: taina-kubishi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taina-kubishi-service-ingress
  namespace: taina-kubishi
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  rules:
    - host: taina.kubishi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taina-kubishi-service
                port:
                  number: 80
    - host: tainacoleman.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taina-kubishi-service
                port:
                  number: 80
  tls:
    - secretName: taina-kubishi-service-cert
      hosts:
        - taina.kubishi.com
    - secretName: taina-kubishi-service-cert-tainacoleman
      hosts:
        - tainacoleman.com
